### ISSUE TITLE
Separate "circle" for separate frames?

### ISSUE THREAD

**Issue by rrnewton** [chimay/torus#9]
I'm loving torus so far, but I tend to create two separate circles: 

* source files for my project, and
* test files for my project.

Then, I want to quickly cycle between the first and the second circle within two separate windows or frames.  (Typically, these are actually under tmux, with the second frame created by `emacsclient -c`.)

However, I find that when I switch circles, the other frame switches circles as well.  I.e. it seems like the active circle is a global-variable.  Is there any way to instead make this state per-frame?

**Comment by chimay** [comment]
It would not be easy to adapt the code ...

Instead of tmux panes, you can use emacs windows and the torus alternate functions : 

torus-alternate : alternate last two files in history
torus-alternate-in-same-torus
torus-alternate-in-same-circle
torus-alternate-in-other-torus
torus-alternate-in-other-circle
torus-alternate-in-same-torus-other-circle

If you alternate to a visible buffer, torus should jump to the matching window and adapt the torus variable accordingly

Example : 

  - open file A in window W_1
  - open and switch to a new window W_2
  - use torus to open file B in window W_2
  - use torus-alternate to bounce between your two files

I suggest you bind the alternate function to a convenient keybinding

**Comment by rrnewton** [comment]
Ah, I think that makes sense.  To expand the example a little bit, the goal is to alternate between {A,B} in W_1 and {C,D} in W_2.

 * Open window W_1 and create circle C_1 with {A,B}
 * Open window W_2 and create circle C_2 with {C,D}
 * When activating window W_n, switch with `torus-alternate-in-same-circle`.

That way, the active file open in a given window ({A,B,C,D}) makes it stay within the appropriate circle ({A,B} or {C,D}).
